### ISSUE TITLE
Story: Rankings ELO

### ISSUE THREAD

**Issue by zambrovski** [holisticon/ranked#1]
As a user I want to be abel to see rankings of all players in a particular discipline sorted by rank.
![wireframe-ranking](https://f.cloud.github.com/assets/673128/445180/cfc01190-b1b5-11e2-90fd-0130068a8a62.png)

The rank should be calculated not solely based on elo-ranking, but similar to tennis ranking in e.g. WTA.

**Comment by jangalinski** [comment]
hey, cool, this is so generic ... we can keep it!

**Comment by jangalinski** [comment]
This is done, we calculate elo and display a ranking
