### ISSUE TITLE
Move configuration into RankedProperties

### ISSUE THREAD

**Issue by zambrovski** [holisticon/ranked#17]
Currently, single properties ale loaded via `@Value` Spring Annotation and then gathered to a single properties object in order to pass around. 

In order to improve readability of the code, implement `@ConfigurationProperties`-way using Kotlin.

**Comment by jangalinski** [comment]
I can have a look at this ...

**Comment by zambrovski** [comment]
The `RankedProperties` is already created inside of the `command` project

**Comment by jangalinski** [comment]
data classes for ConfigurationProperties will be supported in the near future via KotlinBeanBinding, see https://github.com/spring-projects/spring-boot/issues/8762    

It's a non-trivial task and maybe a good idea to just wait for it

**Comment by jangalinski** [comment]
with 35e3c7910debe0229ecf479514b155f5b753a9bd I introduced a new module that combines data class and configurationProperties.
It works, but uses a very simple configuration without nested properties (had to be quick).

will enhance and integrate into backend modules later.

**Comment by zambrovski** [comment]
I vote for waiting until KotlinBeanBinding is released.

**Comment by jangalinski** [comment]
Well, since it’s there and we can’t know for sure if it will come with 2.0, let’s use it
